### ISSUE TITLE
User entity error

### ISSUE THREAD

**Issue by zlydenko** [mikro-orm/nestjs-realworld-example-app#22]
https://github.com/mikro-orm/nestjs-realworld-example-app/blob/fda538790c8ef214855c1b9cb96dff12ca48996e/src/user/user.entity.ts#L22

Property 'id' has no initializer and is not definitely assigned in the constructor. Do we need to manually set an id for each new entity?

**Comment by B4nan** [comment]
Nope, it is autoincrement column. After you flush the entity, the value will be available.
