### ISSUE TITLE
Repository or em injection

### ISSUE THREAD

**Issue by JLN13X** [mikro-orm/nestjs-realworld-example-app#43]
I hope you dont mind asking me here, didnt know any other way...

First of all mikro-orm is amazing and really enjoy working with it so far! Great job!

What is recommend and why?
Injecting all the repositories that you need inside a service OR just injecting the Entity Manager and getting the appropriate repo with `getRepository`? 

Thanks alot

**Comment by B4nan** [comment]
That's really you to you, both is fine, repositories are just thin layer on top of the EM, an extension point if you want, there are no real differences.
