### ISSUE TITLE
`GET /api/articles` returns wrong results

### ISSUE THREAD

**Issue by dpyzo0o** [mikro-orm/nestjs-realworld-example-app#5]
I cloned the example and changed nothing.

This is my current `article` table in the database

<img width="1206" alt="Screen Shot 2020-04-27 at 14 40 52" src="https://user-images.githubusercontent.com/24768249/80341667-76089500-8895-11ea-9faa-d045200761ef.png">

And this is what `GET /api/articles` returns
![Screen Shot 2020-04-27 at 14 41 26](https://user-images.githubusercontent.com/24768249/80341687-80c32a00-8895-11ea-8ff1-47a5c1aa99cd.png)

It just returns the first article three times. I'm new to nestjs and mikro-orm, could you help me out?

**Comment by B4nan** [comment]
The problem was with selecting both articles and users and the fields got overridden as they were not prefixed. Currently QB supports mapping only the root entity.

**Comment by dpyzo0o** [comment]
> The problem was with selecting both articles and users and the fields got overridden as they were not prefixed. Currently QB supports mapping only the root entity.

Thanks for the quick response!
