### ISSUE TITLE
What is meaning of 'RO' in src/article/article.interface.ts?

### ISSUE THREAD

**Issue by wirekang** [mikro-orm/nestjs-realworld-example-app#53]
I found ```ICommentsRO```, ```IArticleRO``` and so on. What is ```RO```? Is this common practice?

**Comment by B4nan** [comment]
This is an example project to showcase the ORM integration, dont be too worried with details. This is not even coming from my head, the project is migrated from the typeorm/nestjs example.

**Comment by B4nan** [comment]
Thanks for the link, first time seeing that abbreviation too :)
