### ISSUE TITLE
Is it possible to inject Nestjs Services into a Mikro-orm Seeder class?

### ISSUE THREAD

**Issue by nikolalukovic** [mikro-orm/nestjs-realworld-example-app#54]
In my case I have tables that reference an objectid from s3. I'd like to upload images to s3 and reference them when seeding the database. Is it possible to inject nestjs services into a Seeder class?

**Comment by B4nan** [comment]
If you want to use nest DI for seeders, you will need to wire it yourself somehow. Most probably you wont be able to use the CLI we have, as it instantiates the seeders and you will need to let nest handle it.
