### ISSUE TITLE
Entity property loses collection type

### ISSUE THREAD

**Issue by dpyzo0o** [mikro-orm/nestjs-realworld-example-app#6]
<img width="465" alt="Screen Shot 2020-04-29 at 15 37 23" src="https://user-images.githubusercontent.com/24768249/80571727-ab48ea80-8a2f-11ea-9afa-4b63dcb78325.png">
<img width="790" alt="Screen Shot 2020-04-29 at 15 38 03" src="https://user-images.githubusercontent.com/24768249/80571731-aedc7180-8a2f-11ea-8f5c-b98edc3f2872.png">

The type inference of property `followers` is missing somehow.

**Comment by B4nan** [comment]
Yeah this happens with circular references sometimes. The type needs to be explicitly specified, I don't know about any other way around:

`followed: Collection<User> = new Collection<User>(this);`
