### ISSUE TITLE
How to mock repositories during unit testing

### ISSUE THREAD

**Issue by rhyek** [mikro-orm/nestjs-realworld-example-app#7]
In the example at https://github.com/mikro-orm/nestjs-realworld-example-app/blob/master/src/tag/tag.controller.spec.ts you are initializing mikroorm with the same config for the database as actually running the app. That seems odd to me.

What is the proper way during unit tests to initialize mikroorm, grab my repository from the IoC container and spy/mock its methods? In my case I just want to mock that and not my service as my service contains my business logic. Thanks.

**Comment by B4nan** [comment]
Entity discovery needs to happen, if you want to work with entities (e.g. you want to work with the [collection wrapper](https://mikro-orm.io/docs/collections/) of some m:n or 1:m relations, or want to have [propagation of changes working](https://mikro-orm.io/docs/propagation/)).

So yes, it is needed, as entity metadata are needed to work with entities. In v4, there is a way to only start the ORM (do the discovery), without connecting to database (there is `connect: boolean` param in `MikroORM.init()` - this will need additional support in the nestjs adapter, but that is not my project).

**Comment by rhyek** [comment]
@B4nan , thanks. For a service method like this:

```typescript
async create(values: CreateTodoDto): Promise<GetTodoDto> {
  const { name, description } = values;
  const todo = new Todo(name, description);
  await this.todoRepository.persist(todo);
  await this.em.flush();
  return todo as GetTodoDto;
}
```

My `todo.service.spec.ts` is initialized like so:

```typescript
beforeEach(async () => {
  const module: TestingModule = await Test.createTestingModule({
    providers: [
      {
        provide: EntityManager,
        useFactory: jest.fn(() => ({
          flush: jest.fn(),
        })),
      },
      {
        provide: getRepositoryToken(Todo),
        useFactory: jest.fn(() => ({
          findAll: jest.fn(),
          findOne: jest.fn(),
          persist: jest.fn(),
        })),
      },
      TodoService,
    ],
  }).compile();

  todoService = module.get<TodoService>(TodoService);
  entityManagerMock = module.get(EntityManager);
  todoRepositoryMock = module.get(getRepositoryToken(Todo));
});
```
and then I just mock the repository methods' implementations in each unit test where applicable. it seems to be working fine. Do you think this approach is correct?

**Comment by B4nan** [comment]
Personally I rather use a real testing database and do integration tests, so not sure if I am the one to help you here :]

Btw all what `EntityRepository` does is to forward the calls to underlying `EntityManager`, so you could mock only the EM methods. (If you plan to use custom repositories, that is a different story for sure.)

**Comment by rhyek** [comment]
alright. yeah i think i have the unit tests down so I'll go ahead and close this. thanks! :-)
