### ISSUE TITLE
feature: Add more tests

### ISSUE THREAD

**Issue by rubiin** [mikro-orm/nestjs-realworld-example-app#8]
Hello there, I justed started using mikro orm with nest. Can you also include unit tests

**Comment by B4nan** [comment]
One example is here: 

https://github.com/mikro-orm/nestjs-realworld-example-app/blob/master/src/tag/tag.controller.spec.ts

**Comment by rubiin** [comment]
> One example is here:
> 
> https://github.com/mikro-orm/nestjs-realworld-example-app/blob/master/src/tag/tag.controller.spec.ts

does it make an actual db connection?

**Comment by B4nan** [comment]
It does connect to the database (in v4 it is possible to not do that via second `init` parameter, in v3 you always need to connect during the `init` phase), but it does not make any queries in the test itself as the repository is mocked. 

https://github.com/mikro-orm/nestjs-realworld-example-app/blob/master/src/tag/tag.controller.spec.ts#L40

**Comment by rubiin** [comment]
cool. I am looking forward for tests on https://github.com/mikro-orm/nestjs-realworld-example-app/blob/master/src/user/user.service.ts

**Comment by B4nan** [comment]
Btw might wanna take a look here (it covers testing too):

https://carlosgonzalez.dev/posts/node-js-di-layered-architecture-and-tdd-a-practical-example-part-1/

**Comment by B4nan** [comment]
closed by #34
